### ISSUE TITLE
Discussão: OLX Portugal 🇵🇹

### ISSUE THREAD

**Issue by OldMetalmind** [FlutterPortugal/noteworthy_portuguese_flutter_apps#5]
## Discussão
Abrir este issue para recolha de informações se a app OLX Portugal ser ou não feita em Flutter.

## Indícios
- Usando a app do Flutter Shark. A aplicação indica que OLX Portugal Android usa vários packages de Flutter, incluindo uma privada chamada `olx_portugal`.
- Já várias pessoas alegam que a [App não é de todo feita com Flutter](https://github.com/FlutterPortugal/noteworthy_portuguese_flutter_apps/pull/3)
- Existem apps que o Flutter Shark não identifica como sendo Flutter 

## Images
![olx_portugal](https://github.com/FlutterPortugal/noteworthy_portuguese_flutter_apps/assets/404874/08f1a30b-90e5-4b78-93fd-d2bdaf26b6b5)

## Flutter Shark App
https://play.google.com/store/apps/details?id=com.fluttershark.fluttersharkapp

**Comment by joaodcp** [comment]
@OldMetalmind Estive agora a escavar e estão, de facto, a utilizar flutter mas em testes A/B, e apenas para o ecrã dos favoritos.

**Comment by OldMetalmind** [comment]
@joaodcp que uso tão interessante de Flutter. Faz sentido então. Obrigado pela partilha.

Até porque a app estava a falhar com o _teste de swipe_ das listas com dois dedos. ( vou ver se encontro a source desta afirmação e já partilho)

**Comment by joaodcp** [comment]
@OldMetalmind Duvidei mesmo por causa do teste falhar.
Será talvez um primeiro passo na transição para flutter? (dependendo dos resultados do A/B)

Aqui fica o código que encontrei (ligeiramente simplificado para facilitar a compreensão):
```kt
boolean isBVariantOfABExperiment = getExperimentHelper().isBVariantOfABExperiment(ExperimentNames.FLUTTER_OBSERVED_POC);
Integer[] numArr = new Integer[4];
numArr[0] = Integer.valueOf(navigation.home);
if (isBVariantOfABExperiment) {
    i = navigation.flutter_favorite;
} else {
    i = navigation.favorite;
}
numArr[1] = Integer.valueOf(i);
numArr[2] = Integer.valueOf(navigation.chat);
numArr[3] = Integer.valueOf(navigation.my_olx);
```

**Comment by OldMetalmind** [comment]
Que excelente pesquisa @joaodcp !
Agora sobre o futuro, e o que irá acontecer concretamente, só saberemos quando a OLX o comunicar.

Com os teus resultados, melhorei o directório principal para contemplar verificações 

https://github.com/FlutterPortugal/noteworthy_portuguese_flutter_apps/blob/main/README.md
